# ========================================
# |    AlathraMobs by ShermansWorld      |
# ========================================

config-version: 2

# =====================================
# |          MOB TIMER SETTINGS       |
# =====================================

# Mob spawn timer interval in seconds
FireGiantTimerInterval: 7200

IceGiantTimerInterval: 10800

StrongGiantTimerInterval: 7200

PackExtension: "terra:overworld/overworld/"