# ========================================
# |    AlathraMobs by ShermansWorld      |
# ========================================

config-version: 1

# =====================================
# |          MOB TIMER SETTINGS       |
# =====================================

# Mob spawn timer interval in seconds
SharkTimerInterval: 60

ElephantTimerInterval: 480

DeerTimerInterval: 480

PackExtension: "terra:overworld/overworld/"